<select name="country_code" id="country_code" class="form-control country_code">
    <option value="93">{{ __('Afghanistan (+93)') }}</option>
    <option value="355">{{ __('Albania (+355)') }}</option>
    <option value="213">{{ __('Algeria (+213)') }}</option>
    <option value="1684">{{ __('American Samoa (+1684)') }}</option> 
    <option value="376">{{ __('Andorra (+376)') }}</option>
    <option value="244">{{ __('Angola (+244)') }}</option>
    <option value="1264">{{ __('Anguilla (+1264)') }}</option>
    <option value="672">{{ __('Antarctica (+672)') }}</option>
    <option value="1268">{{ __('Antigua and Barbuda (+1268)') }}</option>
    <option value="54">{{ __('Argentina (+54)') }}</option>
    <option value="374">{{ __('Armenia (+374)') }}</option>
    <option value="297">{{ __('Aruba (+297)') }}</option>
    <option value="61">{{ __('Australia (+61)') }}</option>
    <option value="43">{{ __('Austria (+43)') }}</option>
    <option value="994">{{ __('Azerbaijan (+994)') }}</option>
    <option value="1242">{{ __('Bahamas (+1242)') }}</option>
    <option value="973">{{ __('Bahrain (+973)') }}</option>
    <option value="880">{{ __('Bangladesh (+880)') }}</option>
    <option value="1246">{{ __('Barbados (+1246)') }}</option>
    <option value="375">{{ __('Belarus (+375)') }}</option>
    <option value="32">{{ __('Belgium (+32)') }}</option>
    <option value="501">{{ __('Belize (+501)') }}</option>
    <option value="229">{{ __('Benin (+229)') }}</option>
    <option value="1441">{{ __('Bermuda (+1441)') }}</option>
    <option value="975">{{ __('Bhutan (+975)') }}</option>
    <option value="591">{{ __('Bolivia (+591)') }}</option>
    <option value="387">{{ __('Bosnia and Herzegovina (+387)') }}</option>
    <option value="267">{{ __('Botswana (+267)') }}</option>
    <option value="55">{{ __('Brazil (+55)') }}</option>
    <option value="246">{{ __('British Indian Ocean Territory (+246)') }}</option>
    <option value="1284">{{ __('British Virgin Islands (+1284)') }}</option>
    <option value="673">{{ __('Brunei (+673)') }}</option>
    <option value="359">{{ __('Bulgaria (+359)') }}</option>
    <option value="226">{{ __('Burkina Faso (+226)') }}</option>
    <option value="257">{{ __('Burundi (+257)') }}</option>
    <option value="855">{{ __('Cambodia (+855)') }}</option>
    <option value="237">{{ __('Cameroon (+237)') }}</option>
    <option value="1">{{ __('Canada (+1)') }}</option>
    <option value="238">{{ __('Cape Verde (+238)') }}</option>
    <option value="1345">{{ __('Cayman Islands (+1345)') }}</option>
    <option value="236">{{ __('Central African Republic (+236)') }}</option>
    <option value="235">{{ __('Chad (+235)') }}</option>
    <option value="56">{{ __('Chile (+56)') }}</option>
    <option value="86">{{ __('China (+86)') }}</option>
    <option value="61">{{ __('Christmas Island (+61)') }}</option>
    <option value="61">{{ __('Cocos Islands (+61)') }}</option>
    <option value="57">{{ __('Colombia (+57)') }}</option>
    <option value="269">{{ __('Comoros (+269)') }}</option>
    <option value="682">{{ __('Cook Islands (+682)') }}</option>
    <option value="506">{{ __('Costa Rica (+506)') }}</option>
    <option value="385">{{ __('Croatia (+385)') }}</option>
    <option value="53">{{ __('Cuba (+53)') }}</option>
    <option value="599">{{ __('Curacao (+599)') }}</option>
    <option value="357">{{ __('Cyprus (+357)') }}</option>
    <option value="420">{{ __('Czech Republic (+420)') }}</option>
    <option value="243">{{ __('Democratic Republic of the Congo (+243)') }}</option>
    <option value="45">{{ __('Denmark (+45)') }}</option>
    <option value="253">{{ __('Djibouti (+253)') }}</option>
    <option value="1767">{{ __('Dominica (+1767)') }}</option>
    <option value="1809">{{ __('Dominican Republic (+1809)') }}</option>
    <option value="1829">{{ __('Dominican Republic (+1829)') }}</option>
    <option value="1849">{{ __('Dominican Republic (+1849)') }}</option>
    <option value="670">{{ __('East Timor (+670)') }}</option>
    <option value="593">{{ __('Ecuador (+593)') }}</option>
    <option value="20">{{ __('Egypt (+20)') }}</option>
    <option value="503">{{ __('El Salvador (+503)') }}</option>
    <option value="240">{{ __('Equatorial Guinea (+240)') }}</option>
    <option value="291">{{ __('Eritrea (+291)') }}</option>
    <option value="372">{{ __('Estonia (+372)') }}</option>
    <option value="251">{{ __('Ethiopia (+251)') }}</option>
    <option value="500">{{ __('Falkland Islands (+500)') }}</option>
    <option value="298">{{ __('Faroe Islands (+298)') }}</option>
    <option value="679">{{ __('Fiji (+679)') }}</option>
    <option value="358">{{ __('Finland (+358)') }}</option>
    <option value="33">{{ __('France (+33)') }}</option>
    <option value="689">{{ __('French Polynesia (+689)') }}</option>
    <option value="241">{{ __('Gabon (+241)') }}</option>
    <option value="220">{{ __('Gambia (+220)') }}</option>
    <option value="995">{{ __('Georgia (+995)') }}</option>
    <option value="49">{{ __('Germany (+49)') }}</option>
    <option value="233">{{ __('Ghana (+233)') }}</option>
    <option value="350">{{ __('Gibraltar (+350)') }}</option>
    <option value="30">{{ __('Greece (+30)') }}</option>
    <option value="299">{{ __('Greenland (+299)') }}</option>
    <option value="1473">{{ __('Grenada (+1473)') }}</option>
    <option value="1671">{{ __('Guam (+1671)') }}</option>
    <option value="502">{{ __('Guatemala (+502)') }}</option>
    <option value="224">{{ __('Guinea (+224)') }}</option>
    <option value="245">{{ __('Guinea-Bissau (+245)') }}</option>
    <option value="592">{{ __('Guyana (+592)') }}</option>
    <option value="509">{{ __('Haiti (+509)') }}</option>
    <option value="504">{{ __('Honduras (+504)') }}</option>
    <option value="852">{{ __('Hong Kong (+852)') }}</option>
    <option value="36">{{ __('Hungary (+36)') }}</option>
    <option value="354">{{ __('Iceland (+354)') }}</option>
    <option value="91" selected>{{ __('India (+91)') }}</option>
    <option value="62">{{ __('Indonesia (+62)') }}</option>
    <option value="98">{{ __('Iran (+98)') }}</option>
    <option value="964">{{ __('Iraq (+964)') }}</option>
    <option value="353">{{ __('Ireland (+353)') }}</option>
    <option value="972">{{ __('Israel (+972)') }}</option>
    <option value="39">{{ __('Italy (+39)') }}</option>
    <option value="225">{{ __('Ivory Coast (+225)') }}</option>
    <option value="1876">{{ __('Jamaica (+1876)') }}</option>
    <option value="81">{{ __('Japan (+81)') }}</option>
    <option value="962">{{ __('Jordan (+962)') }}</option>
    <option value="7">{{ __('Kazakhstan (+7)') }}</option>
    <option value="254">{{ __('Kenya (+254)') }}</option>
    <option value="686">{{ __('Kiribati (+686)') }}</option>
    <option value="383">{{ __('Kosovo (+383)') }}</option>
    <option value="965">{{ __('Kuwait (+965)') }}</option>
    <option value="996">{{ __('Kyrgyzstan (+996)') }}</option>
    <option value="856">{{ __('Laos (+856)') }}</option>
    <option value="371">{{ __('Latvia (+371)') }}</option>
    <option value="961">{{ __('Lebanon (+961)') }}</option>
    <option value="266">{{ __('Lesotho (+266)') }}</option>
    <option value="231">{{ __('Liberia (+231)') }}</option>
    <option value="218">{{ __('Libya (+218)') }}</option>
    <option value="423">{{ __('Liechtenstein (+423)') }}</option>
    <option value="370">{{ __('Lithuania (+370)') }}</option>
    <option value="352">{{ __('Luxembourg (+352)') }}</option>
    <option value="853">{{ __('Macau (+853)') }}</option>
    <option value="389">{{ __('Macedonia (+389)') }}</option>
    <option value="261">{{ __('Madagascar (+261)') }}</option>
    <option value="265">{{ __('Malawi (+265)') }}</option>
    <option value="60">{{ __('Malaysia (+60)') }}</option>
    <option value="960">{{ __('Maldives (+960)') }}</option>
    <option value="223">{{ __('Mali (+223)') }}</option>
    <option value="356">{{ __('Malta (+356)') }}</option>
    <option value="692">{{ __('Marshall Islands (+692)') }}</option>
    <option value="222">{{ __('Mauritania (+222)') }}</option>
    <option value="230">{{ __('Mauritius (+230)') }}</option>
    <option value="262">{{ __('Mayotte (+262)') }}</option>
    <option value="52">{{ __('Mexico (+52)') }}</option>
    <option value="691">{{ __('Micronesia (+691)') }}</option>
    <option value="373">{{ __('Moldova (+373)') }}</option>
    <option value="377">{{ __('Monaco (+377)') }}</option>
    <option value="976">{{ __('Mongolia (+976)') }}</option>
    <option value="382">{{ __('Montenegro (+382)') }}</option>
    <option value="1664">{{ __('Montserrat (+1664)') }}</option>
    <option value="212">{{ __('Morocco (+212)') }}</option>
    <option value="258">{{ __('Mozambique (+258)') }}</option>
    <option value="95">{{ __('Myanmar (+95)') }}</option>
    <option value="264">{{ __('Namibia (+264)') }}</option>
    <option value="674">{{ __('Nauru (+674)') }}</option>
    <option value="977">{{ __('Nepal (+977)') }}</option>
    <option value="31">{{ __('Netherlands (+31)') }}</option>
    <option value="599">{{ __('Netherlands Antilles (+599)') }}</option>
    <option value="687">{{ __('New Caledonia (+687)') }}</option>
    <option value="64">{{ __('New Zealand (+64)') }}</option>
    <option value="505">{{ __('Nicaragua (+505)') }}</option>
    <option value="227">{{ __('Niger (+227)') }}</option>
    <option value="234">{{ __('Nigeria (+234)') }}</option>
    <option value="683">{{ __('Niue (+683)') }}</option>
    <option value="672">{{ __('Norfolk Island (+672)') }}</option>
    <option value="850">{{ __('North Korea (+850)') }}</option>
    <option value="1670">{{ __('Northern Mariana Islands (+1670)') }}</option>
    <option value="47">{{ __('Norway (+47)') }}</option>
    <option value="968">{{ __('Oman (+968)') }}</option>
    <option value="92">{{ __('Pakistan (+92)') }}</option>
    <option value="680">{{ __('Palau (+680)') }}</option>
    <option value="970">{{ __('Palestine (+970)') }}</option>
    <option value="507">{{ __('Panama (+507)') }}</option>
    <option value="675">{{ __('Papua New Guinea (+675)') }}</option>
    <option value="595">{{ __('Paraguay (+595)') }}</option>
    <option value="51">{{ __('Peru (+51)') }}</option>
    <option value="63">{{ __('Philippines (+63)') }}</option>
    <option value="64">{{ __('Pitcairn (+64)') }}</option>
    <option value="48">{{ __('Poland (+48)') }}</option>
    <option value="351">{{ __('Portugal (+351)') }}</option>
    <option value="1787">{{ __('Puerto Rico (+1787)') }}</option>
    <option value="1939">{{ __('Puerto Rico (+1939)') }}</option>
    <option value="974">{{ __('Qatar (+974)') }}</option>
    <option value="242">{{ __('Republic of the Congo (+242)') }}</option>
    <option value="262">{{ __('Reunion (+262)') }}</option>
    <option value="40">{{ __('Romania (+40)') }}</option>
    <option value="7">{{ __('Russia (+7)') }}</option>
    <option value="250">{{ __('Rwanda (+250)') }}</option>
    <option value="590">{{ __('Saint Barthelemy (+590)') }}</option>
    <option value="290">{{ __('Saint Helena (+290)') }}</option>
    <option value="1869">{{ __('Saint Kitts and Nevis (+1869)') }}</option>
    <option value="1758">{{ __('Saint Lucia (+1758)') }}</option>
    <option value="590">{{ __('Saint Martin (+590)') }}</option>
    <option value="508">{{ __('Saint Pierre and Miquelon (+508)') }}</option>
    <option value="1784">{{ __('Saint Vincent and the Grenadines (+1784)') }}</option>
    <option value="685">{{ __('Samoa (+685)') }}</option>
    <option value="378">{{ __('San Marino (+378)') }}</option>
    <option value="239">{{ __('Sao Tome and Principe (+239)') }}</option>
    <option value="966">{{ __('Saudi Arabia (+966)') }}</option>
    <option value="221">{{ __('Senegal (+221)') }}</option>
    <option value="381">{{ __('Serbia (+381)') }}</option>
    <option value="248">{{ __('Seychelles (+248)') }}</option>
    <option value="232">{{ __('Sierra Leone (+232)') }}</option>
    <option value="65">{{ __('Singapore (+65)') }}</option>
    <option value="1721">{{ __('Sint Maarten (+1721)') }}</option>
    <option value="421">{{ __('Slovakia (+421)') }}</option>
    <option value="386">{{ __('Slovenia (+386)') }}</option>
    <option value="677">{{ __('Solomon Islands (+677)') }}</option>
    <option value="252">{{ __('Somalia (+252)') }}</option>
    <option value="27">{{ __('South Africa (+27)') }}</option>
    <option value="82">{{ __('South Korea (+82)') }}</option>
    <option value="211">{{ __('South Sudan (+211)') }}</option>
    <option value="34">{{ __('Spain (+34)') }}</option>
    <option value="94">{{ __('Sri Lanka (+94)') }}</option>
    <option value="249">{{ __('Sudan (+249)') }}</option>
    <option value="597">{{ __('Suriname (+597)') }}</option>
    <option value="47">{{ __('Svalbard and Jan Mayen (+47)') }}</option>
    <option value="268">{{ __('Swaziland (+268)') }}</option>
    <option value="46">{{ __('Sweden (+46)') }}</option>
    <option value="41">{{ __('Switzerland (+41)') }}</option>
    <option value="963">{{ __('Syria (+963)') }}</option>
    <option value="886">{{ __('Taiwan (+886)') }}</option>
    <option value="992">{{ __('Tajikistan (+992)') }}</option>
    <option value="255">{{ __('Tanzania (+255)') }}</option>
    <option value="66">{{ __('Thailand (+66)') }}</option>
    <option value="670">{{ __('Timor-Leste (+670)') }}</option>
    <option value="228">{{ __('Togo (+228)') }}</option>
    <option value="690">{{ __('Tokelau (+690)') }}</option>
    <option value="676">{{ __('Tonga (+676)') }}</option>
    <option value="1868">{{ __('Trinidad and Tobago (+1868)') }}</option>
    <option value="216">{{ __('Tunisia (+216)') }}</option>
    <option value="90">{{ __('Turkey (+90)') }}</option>
    <option value="993">{{ __('Turkmenistan (+993)') }}</option>
    <option value="1649">{{ __('Turks and Caicos Islands (+1649)') }}</option>
    <option value="688">{{ __('Tuvalu (+688)') }}</option>
    <option value="256">{{ __('Uganda (+256)') }}</option>
    <option value="380">{{ __('Ukraine (+380)') }}</option>
    <option value="971">{{ __('United Arab Emirates (+971)') }}</option>
    <option value="44">{{ __('United Kingdom (+44)') }}</option>
    <option value="1">{{ __('United States (+1)') }}</option>
    <option value="598">{{ __('Uruguay (+598)') }}</option>
    <option value="998">{{ __('Uzbekistan (+998)') }}</option>
    <option value="678">{{ __('Vanuatu (+678)') }}</option>
    <option value="379">{{ __('Vatican (+379)') }}</option>
    <option value="58">{{ __('Venezuela (+58)') }}</option>
    <option value="84">{{ __('Vietnam (+84)') }}</option>
    <option value="681">{{ __('Wallis and Futuna (+681)') }}</option>
    <option value="967">{{ __('Yemen (+967)') }}</option>
    <option value="260">{{ __('Zambia (+260)') }}</option>
    <option value="263">{{ __('Zimbabwe (+263)') }}</option>
</select>
